services:
  server:
    build:
      context: .
      target: final
    ports:
      - 3000:3000
    env_file:
        - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 10.0.0.3
      frontend:
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ulpn
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      backend:
        ipv4_address: 10.0.0.2

volumes:
  db-data:

secrets:
  db-password:
    file: secrets/db/password.txt

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
  frontend:
    driver: bridge

