services:
  database:
    image: postgres:16.2
    restart: always
    ports:
      - 5432:5432
    env_file: ./database.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 10.0.0.2
  api:
    build:
      context: ./api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      backend:
        ipv4_address: 10.0.0.3
      frontend:

volumes:
  db-data:

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/29
          gateway: 10.0.0.1
  frontend:
    driver: bridge

